### ISSUE TITLE
Proposal: containerize the development environment

### ISSUE THREAD

**Issue by krancour** [deis/builder#1]
This is to lower the barrier to entry for hacking on Deis while also standardizing the development environment for all contributors.

**Comment by smothiki** [comment]
@krancour Right now I'm building everything on single make target for each builder type.
In future once things gets settled down with builder I will make proper targets for docker build and docker push. let me know if you have any idea

**Comment by arschles** [comment]
@krancour I believe this is done. [The Makefile](https://github.com/deis/builder/blob/master/Makefile)'s `build` and `test` targets execute everything inside of `quay.io/deis/go-dev:0.3.0` containers.

Closing. Can you reopen this if you think there's more to be done?

**Comment by krancour** [comment]
@arschles :100:
