### ISSUE TITLE
Error pushing

### ISSUE THREAD

**Issue by aledbf** [deis/builder#116]
```
$ git push deis master
Counting objects: 490, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (166/166), done.
Writing objects: 100% (490/490), 140.76 KiB | 0 bytes/s, done.
Total 490 (delta 306), reused 490 (delta 306)
Running in debug mode
Running git hook
read [0000000000000000000000000000000000000000,6e3bc01dd7494525d5502900260fc4dc908bd0a8,refs/heads/master]
remote: [ERROR] running git receive hook [Deis controller endpoint http://10.3.2.71:80/v2/hooks/push: expected status code 201, got 401]
Workflow request /v2/hooks/push (body elided)
To ssh://git@deis-v2:2222/srv-f22.git
 * [new branch]      master -> master
```

Any advice on how to debug this error?

**Comment by arschles** [comment]
Hi @aledbf - thanks for asking. First, are you running from a Helm chart, and if so, which one?

**Comment by aledbf** [comment]
@arschles no helm, just kubectl with code from master.
adding debug I see this:
```
Workflow request /v2/hooks/push (body elided)
request headers: map[Content-Type:[application/json] Accept:[application/json] User-Agent:[deis-builder] X-Deis-Builder-Auth:[Lcvz3A7K9GK2TTtkKDq52uTCwHkFXEzAY3KFfXVDP7y6YdPXsCaTrzNCu6h5KJ7g
]]
remote: running git receive hook [Deis controller endpoint http://10.3.2.71:80/v2/hooks/push: expected status code 201, got 401]
request body:
```

I will check the builderKey generation (the new line is strange)

**Comment by arschles** [comment]
@aledbf got it, thanks. I'm assuming you're using the [manifest in this repo](https://github.com/deis/builder/blob/master/manifests/deis-builder-rc.yaml), which uses `v2-beta`. Are you also using a `v2-beta` `deis/workflow` image in that pod?

**Comment by arschles** [comment]
For some background, workflow and builder agree on a key for builder to authenticate to workflow to publish a build. It's stored in a Kubernetes secret and mounted [here](https://github.com/deis/builder/blob/master/manifests/deis-builder-rc.yaml#L53). That secret is generated [here](https://github.com/deis/charts/blob/master/deis-dev/tpl/deis-workflow-secret-builder-key-auth.yaml).

All that being said, can you `kubectl exec` into your workflow and builder pods and ensure that the secrets match?

**Comment by aledbf** [comment]
@arschles the secrets match
```
$ kubectl exec -it deis-workflow-o031n --namespace=deis cat /var/run/secrets/api/builder/auth/builder-key
Lcvz3A7K9GK2TTtkKDq52uTCwHkFXEzAY3KFfXVDP7y6YdPXsCaTrzNCu6h5KJ7g
$ kubectl exec -it deis-builder-z4emb --namespace=deis cat /var/run/secrets/api/auth/builder-key
Lcvz3A7K9GK2TTtkKDq52uTCwHkFXEzAY3KFfXVDP7y6YdPXsCaTrzNCu6h5KJ7g
```

code of workflow and builder from current master

**Comment by arschles** [comment]
@aledbf would you mind curling to the workflow pod with that header? I'd like to use that as a test to determine if workflow is running properly, independently of the builder code

**Comment by aledbf** [comment]
@arschles I change the go code and added a log during the validation in `deis/workflow`.

```
ERROR invalid auth header "Lcvz3A7K9GK2TTtkKDq52uTCwHkFXEzAY3KFfXVDP7y6YdPXsCaTrzNCu6h5KJ7g" - "Lcvz3A7K9GK2TTtkKDq52uTCwHkFXEzAY3KFfXVDP7y6YdPXsCaTrzNCu6h5KJ7g
"
```

```
    def has_permission(self, request, view):
        """
        Return `True` if permission is granted, `False` otherwise.
        """
        auth_header = request.environ.get('HTTP_X_DEIS_BUILDER_AUTH')
        if not auth_header:
            logger.error('auth header is missing')
            return False
        valid_header = auth_header == settings.BUILDER_KEY
        if not valid_header:
            logger.error('invalid auth header "{}" - "{}"'
                .format(auth_header, settings.BUILDER_KEY))
            return False
        else:
            return True
```

The new line is also present in `deis/workflow` (I don't see such new line even with vi)

**Comment by arschles** [comment]
Oh, I see. Good find. Did you change the Go code to remove a newline? Or do you mean you changed the python code in controller? Builder doesn't do anything special with the builder key (such as remove newlines, etc...).

@helgi do you know why controller would receive the builder key with a newline in it?

**Comment by aledbf** [comment]
Closing, my fault. I forgot to add `-n` in the `echo` that generates the secrets.
Sorry for the noise.

**Comment by arschles** [comment]
No problem, thanks!

**Comment by aledbf** [comment]
@arschles this error was hard to find. Perhaps it might be a good idea to check that the secret does not contain invalid characters? (like newline)

**Comment by arschles** [comment]
@aledbf yes, we can do a sanity check for common mistakes like newline.

However, how did the secret change between workflow and builder? I'd like to understand that because afaik the common case is for the secret to be stored once in Kubernetes and mounted to each consuming service (in this case, builder and workflow).

**Comment by helgi** [comment]
Good point - I didn't add any special handling for it since I was using `helm` to generate the secret via `helm generate deis-dev` before the `helm install`. We can add `strip` or similar in the controller, and likewise in builder
