### ISSUE TITLE
Defaults to docker build if no Procfile found?

### ISSUE THREAD

**Issue by olalonde** [deis/builder#124]
I believe the README is incorrect:

> If a Dockerfile is present, starts a dockerbuilder pod, configured to download the code to build from the > URL computed in the previous step (dockerbuilder and Dockerfile builder are not currently supported. > See https://github.com/deis/dockerbuilder/pull/1 for prototype dockerbuilder code).
> 
> Otherwise, starts a slugbuilder pod, configured to download the code to build from the URL computed in the previous step.

It seems like the current code *defaults* to dockerbuilder and will only use slugbuilder if a Procfile is found. This is a different behaviour from deis v1 which defaulted to slugbuilder and only used dockerbuilder if a Dockerfile was found.

https://github.com/deis/builder/blob/439d2e9033877e380b70ad53eaf0bdd8da26a104/pkg/gitreceive/build.go#L126

**Comment by arschles** [comment]
@olalonde ah yes, you're right - thanks! I'd like to keep builder's behavior similar in this category to v1. Tomorrow, I'll be changing the code and docs as you said.
