### ISSUE TITLE
Build fails with "Unable to select a buildpack"

### ISSUE THREAD

**Issue by olalonde** [deis/builder#126]
Steps to reproduce

```
git clone https://github.com/RocketChat/Rocket.Chat.git
cd Rocket.Chat
deis create rocket
deis config:set BUILDPACK_URL=https://github.com/RocketChat/heroku-buildpack-meteor
# also tested
# deis config:set BUILDPACK_URL=https://github.com/RocketChat/heroku-buildpack-meteor.git
git push deis
```

```
$ kd logs rocket-git-465797e7
-----> Unable to select a buildpack
```

Additionally, any subsequent `git push` will fail unless `rocket-git-465797e7` is manually deleted with `kd delete pod rocket-git-465797e7` and the builder restarted with `kd delete pod deis-builder-4bvr5` (or `kd delete pod $(kd get pods | grep deis-builder | cut -f 1  -d " ")`).

**Comment by olalonde** [comment]
Might be related to https://github.com/deis/builder/issues/123 (environment variables not available during build)

**Comment by bacongobbler** [comment]
Yes that sounds very relevant. BUILDPACK_URL is fetched during the build IIRC. I tested custom buildpacks earlier and they worked last week so maybe something recent broke it.

**Comment by arschles** [comment]
@bacongobbler @olalonde looks like it regressed, as I tested custom buildpacks last week and they worked as well. Will look at it this week and add a test once it's fixed.

**Comment by arschles** [comment]
@olalonde if you run builder with `DEBUG=1`, do you see a line like "found custom buildpack URL xyz"?

**Comment by olalonde** [comment]
@arschles do you mean `DEBUG=1 git push deis`?

**Comment by olalonde** [comment]
FWIW, it seems the buildpack I was trying to use doesn't work on CoreOS/docker anyways... maybe that's what was causing the problem? https://github.com/coreos/bugs/issues/1095

**Comment by bacongobbler** [comment]
That doesn't seem to be the problem. If we hit that issue, the buildpack wouldve been fetched and you wouldve seen log output from the build.

**Comment by arschles** [comment]
@olalonde sorry, I meant running the builder Replication Controller with `DEBUG` set to `"1"` in the environment variables. You'd add the following under the `env:` section in the yaml:

```yaml
- name: DEBUG
  value: "1"
```

**Comment by arschles** [comment]
also, I believe what @bacongobbler says is right. The builder should start up a pod running a [slugbuilder](https://github.com/deis/slugbuilder), which should be passed the custom buildpack URL in the environment. It looks like that is not happening for whatever reason.

Also, @olalonde which image tag of builder and [deis/workflow](https://github.com/deis/workflow) are you using?

**Comment by olalonde** [comment]
I [installed it](https://gist.github.com/arschles/5b7a75a50938913d3eb1#1-install-deis-cluster) using helm:

```bash
$ helm list
--->    deis (deis 2.0.0-alpha) - For testing only!
--->    deis-lite (deis-lite 2.0.0-alpha) - For testing only!
```

**Comment by bacongobbler** [comment]
@olalonde would you mind trying the following off master?

First, you'll need to install Helm v0.3, then run the following

```
helm uninstall deis
helm update
helm generate deis-dev
helm install deis-dev
```

Then try again and verify if you're seeing this on master. It's possible that this was fixed recently (2.0-alpha was released before New Year's, so in terms of velocity for 2.0-stable it's ancient) ;)

**Comment by olalonde** [comment]
@bacongobbler yes happy to do so, just wasn't sure how to do it :+1:

**Comment by smothiki** [comment]
@olalonde  are you still facing the issue.

**Comment by olalonde** [comment]
Oh sorry, didn't have time to test... Guess you can close the issue and I'll comment here if it still fails!

**Comment by arschles** [comment]
Thanks @olalonde. Closing
