### ISSUE TITLE
add to CI

### ISSUE THREAD

**Issue by arschles** [deis/builder#13]
just as [other](https://github.com/deis/workflow) [repos](https://github.com/deis/router) do, travis.ci needs to build this codebase. since the build needs to push to dockerhub and quay.io, this issue implicitly will require a makefile refactor. see https://github.com/deis/minio/pull/9/files#r46733280 for more

**Comment by mboersma** [comment]
This was implemented in #10, so I'm closing this.

**Comment by arschles** [comment]
missed that, thanks @mboersma
