### ISSUE TITLE
Proposal: refactor cookoo out of the builder

### ISSUE THREAD

**Issue by arschles** [deis/builder#152]
I believe that `github.com/Masterminds/cookoo` represents a barrier to entry and therefore raises the barrier to entry for contributions to the builder codebase. Removing it as a dependency would lower this barrier.

@technosophos thoughts? @smothiki I know that you were considering doing this refactor.

**Comment by smothiki** [comment]
Out of scope for v2 beta. So stopped thinking about it

**Comment by technosophos** [comment]
I agree that we should do it. And I agree that it has to be post-v2.0.0.

**Comment by krancour** [comment]
Speaking for myself, that would make me more comfortable hacking on builder as well.  Big +1

**Comment by aledbf** [comment]
:+1:

**Comment by kmala** [comment]
fixed in #316
