### ISSUE TITLE
Race condition when builder attempts to find slugbuilder pods

### ISSUE THREAD

**Issue by slack** [deis/builder#156]
`git push` was rejected because builder was unable to watch for pod events.

Logs available at https://gist.github.com/slack/f5056d6abe5b17e2c69d

**Comment by slack** [comment]
This bit me for a number of deploys off the bat but is now working as intended.

We should probably retry on 404 for a pod that we know should exist.

**Comment by smothiki** [comment]
have to do appropriate changes in builder https://github.com/deis/workflow/pull/346

**Comment by arschles** [comment]
@smothiki @slack I'm confused by the scope of this issue. The issue in deis/workflow#346 is unrelated to the race condition that's described here.

Also, #166 seems to solve the race condition described here. Can anyone confirm?

**Comment by slack** [comment]
Yeah, I don't think deis/workflow#346 is related. I haven't tested since #166 was merged. I'll test with current v2-beta images and see what falls out.

**Comment by slack** [comment]
Deployed deis-dev images as of today and was unable to repo `attempting to stream logs` issue after 7 deploys. I'll go ahead and close!

**Comment by arschles** [comment]
@slack I'm ok with leaving this closed for now, but it's a race so it could still be around. If you see failures again please reopen or file a new issue.

**Comment by slack** [comment]
Certainly, I'll pipe up if I see it again!

**Comment by arschles** [comment]
Thanks. And I believe that @gabrtv saw an error that looked suspiciously like a race yesterday. I don't recall details, and couldn't tell at the time if a race was definitely to blame. Anyway, given our polling interval the race is _unlikely_ but I have a prototype [here](https://github.com/deis/builder/pull/185) that, in theory, would remove any potential race.

**Comment by slack** [comment]
This bad larry popped up again:
```
k:beef example-go [master]$ git commit -m "Bump" --allow-empty && git push deis master
[master c0d91cd] Bump
Warning: Permanently added the RSA host key for IP address '[52.89.89.224]:2222' to the list of known hosts.
Counting objects: 98, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (93/93), done.
Writing objects: 100% (98/98), 19.29 KiB | 0 bytes/s, done.
Total 98 (delta 53), reused 0 (delta 0)
remote: ---> 2016/02/22 20:39:24 Error running git receive hook [watching events for builder pod startup (pods "slugbuild-earthy-instinct-c0d91cd9-cd33644e" not found)]
Starting build... but first, coffee!
To ssh://git@deis.beef.slack.io:2222/earthy-instinct.git
 * [new branch]      master -> master
k:beef example-go [master]$
```

**Comment by krancour** [comment]
I'm running into this as well on the new staging-2 cluster.

**Comment by jchauncey** [comment]
this is definitely reproducible on the staging-2 cluster

**Comment by mboersma** [comment]
I'm seeing this > 50% of the time when running the e2e tests locally.

**Comment by smothiki** [comment]
closing this in favor of https://github.com/deis/builder/pull/198.
Please feel free to reopen if issue is not fixed
