### ISSUE TITLE
[Proposal]: add a secret to store the builder ssh keys

### ISSUE THREAD

**Issue by aledbf** [deis/builder#157]
Right now `deis/builder` stores/uses the keys in etcd. After #148 there's no place to store the keys.

**Comment by arschles** [comment]
@aledbf after #148, wouldn't the keys be stored only inside the controller, and accessed via the controller hooks API?

**Comment by aledbf** [comment]
@arschles I mean the ssh keys located in /etc/ssh used in the builder in the ssh session. If we don't add this feature every time the builder is started it will use a different key

**Comment by arschles** [comment]
Ah, you're talking about host keys here. Missed that, thanks.

**Comment by technosophos** [comment]
I agree. Without this, it'll get really annoying to users when a pod gets restarted.

**Comment by technosophos** [comment]
We'd have to have Helm generate the host keys on the fly, btw, otherwise we'd have a security issue. (Or we could figure out another way to dynamically generate them.)

**Comment by arschles** [comment]
I think this is ok as long as we continue to run builder with `replicas: 1`, which IIRC is our working assumption at least for beta.

**Comment by arschles** [comment]
Also, +1 on using `helm generate` to generate host keys on the fly. We can also fail to launch builder if keys aren't present in the secret. I think (although I haven't done an audit) that doing so will remove builder's dependency on `ssh-keygen`, as it currently attempts to generate new keys if none are found in etcd (which they won't ever be after #148)

**Comment by smothiki** [comment]
@arschles @aledbf I think we are calling controller for ssh key validation which are stored in database.
I think we should close this issue

**Comment by helgi** [comment]
Other option is instead of doing the HTTP ping is to look for the keys in a predefined secret(s) (or discoverable one) that controller writes to

**Comment by arschles** [comment]
If you `git push` to the builder, `delete` the pod, let it restart, and then try the `git push` again, the push will fail with a host validation error. @helgi are you suggesting that when the builder comes up we populate the host key from a value gotten from the controller? If so, what benefit does that give over a `helm generate`d key?

**Comment by helgi** [comment]
You are talking about the builder to API auth token, I was referring to the ssh keys. Probably an overkill anyway for now

**Comment by arschles** [comment]
@helgi nope, talking about the SSH host keys, and suggesting that we store them in the same manner that we store the builder -> API auth token. See discussion [above](https://github.com/deis/builder/issues/157#issuecomment-181973651)

**Comment by bacongobbler** [comment]
To be completely clear:

 - @helgi @smothiki you are talking about `deis keys`, which is the **user's** SSH public keys
 - @arschles and @aledbf are talking about the builder's SSH private keys

The latter is what we need to write out to a secret. I'll tackle this.

**Comment by bacongobbler** [comment]
@technosophos how does introducing new template functions to helm for generating said private keys sound to you, or does that sound a little extravagant for helm?

**Comment by bacongobbler** [comment]
I just booted up a builder and [copied the base64 encoded SSH keys into the secret](https://gist.github.com/bacongobbler/939f8d097caeb5dda5d63a2a16cce4ec) hoping we could use that, but it looks like we can't base64 encode the host keys into a secret because the maximum length allowed is 253 characters for a secret, so the idea of introducing a function is shot out of the pond.

Logs from `helm install`:

```
The Secret "builder-ssh-private-keys" is invalid.

* data[ssh_host_ecdsa_key]: Invalid value: "ssh_host_ecdsa_key": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
* data[ssh_host_ed25519_key]: Invalid value: "ssh_host_ed25519_key": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
* data[ssh_host_rsa_key]: Invalid value: "ssh_host_rsa_key": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
* data[ssh_host_dsa_key]: Invalid value: "ssh_host_dsa_key": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
```

**Comment by aledbf** [comment]
@bacongobbler the issue is with the key `ssh_host_rsa_key` should be `ssh-host-rsa-key`

**Comment by helgi** [comment]
Dealt with the same thing in https://github.com/deis/controller/blob/master/rootfs/scheduler/__init__.py#L593

**Comment by bacongobbler** [comment]
oops, my mistake. Good catch. The error seemed to allude to the `value` being the issue rather than the key itself. I should've caught that.

**Comment by smothiki** [comment]
https://github.com/deis/builder/blob/master/pkg/sshd/sshd.go#L31 here we are adding three keys ecdsa , rsa, dsa . So if we can generate them as secrets problem solved. Also do we need 3 types of auth keys ?

**Comment by bacongobbler** [comment]
@smothiki the more the better, so yes. Some users have ecdsa public keys, so we need an ecdsa private key to match for signing.

**Comment by smothiki** [comment]
Easy solution would be asking users to generate what type of key they want ? or default generates all three types of keys

**Comment by bacongobbler** [comment]
the builder generated all three types of keys. I'm currently just hardcoding a `base64`-encoded rsa, dsa and ecdsa private key into a secret with the intent to write template functions for helm to generate these keys for us in the future.

**Comment by smothiki** [comment]
That would mean that its the same key for every builder install which arises security issues. 
Just by knowing a router IP anyone can access builder. rather generate a secret randomly is the best option

**Comment by bacongobbler** [comment]
Yes, I'm aware of the issue that it's a security issue. This is just the initial PR, and I am currently working on the templating on helm's end separately. Just splitting them out into different units of work so it's easier to review.

**Comment by smothiki** [comment]
better implement everything at once rather than hardcoding keys. I'm okay if you think the helm generate stuff lands in beta3 which replaces the hardcoded values
