### ISSUE TITLE
BuilderPodWaitDuration should be more than 5 minutes

### ISSUE THREAD

**Issue by bacongobbler** [deis/builder#205]
After the [BuilderPodWaitDuration](https://github.com/deis/builder/blob/f51d3a2fb374f12f04c45d941362c4f5c6c5ae23/pkg/gitreceive/config.go#L30) time is up, the build is considered a failure and the git push fails. Many buildpack deployments (such as ruby with a database migration task or an assets:precompile task) take more than 5 minutes. Even on slow internet speeds a Dockerfile build could more than easily take longer than 5 minutes.

I don't think there should be a wait duration at all for builds.

**Comment by arschles** [comment]
@bacongobbler I think we certainly should have a wait duration for all builds to account for the variety of failure modes that render the builder pod stuck or unable to communicate over the network to the resources it needs. It's configurable now, but I'm ok defaulting it to a much higher number. My guess is that 20 minutes is well over double the amount of time to build any codebase on any reasonanbly modern machine & network connection.

Thoughts?

**Comment by bacongobbler** [comment]
I'd be okay with having a higher default. My information was wrong; apparently Heroku as [a slug compilation time limit of 15 minutes](https://devcenter.heroku.com/articles/slug-compiler) so as long as we have parity with them I'm okay with that being the time limit.

**Comment by arschles** [comment]
Ah, good to know - didn't even think to look @ Heroku's docs. PR incoming for upping the default to 15 minutes.
