### ISSUE TITLE
Handle error case when repository lock unlock fails

### ISSUE THREAD

**Issue by arschles** [deis/builder#220]
One possible fix is that the lock can become a lease.

Ref https://github.com/deis/builder/pull/212#discussion_r54755134

**Comment by arschles** [comment]
Moving to RC1

**Comment by arschles** [comment]
Looks like https://github.com/deis/builder/commit/aa7defbf1eeaf2243aee1786783148d0ec955d56 accidentally marked this as fixed. Reopening

**Comment by arschles** [comment]
bumping from RC1, as this is not critical for the RC

**Comment by mboersma** [comment]
Was this fixed by #367?

**Comment by arschles** [comment]
Yes. Closing
