### ISSUE TITLE
[Proposal]: allow the use of imagePullSecrets

### ISSUE THREAD

**Issue by aledbf** [deis/builder#221]
This is required to pull images from a private registry with authentication
Just in case I mean just the name, not the creation
```
        env:
            - name: "PULL_SECRETS"
              value: "priv-reg1,priv-reg2"
```

The previous example assumes that the required secret already exists
````
kubectl create secret docker-registry <name (priv-reg1)> \
	--docker-server=<url> \
	--docker-username=<username> \
	--docker-password=<pass> \
	--namespace deis
```

**Comment by kmala** [comment]
private registry support is added in deis https://github.com/deis/workflow/pull/400
