### ISSUE TITLE
Use deis-objectstorage-secret.yaml to get S3 credentials

### ISSUE THREAD

**Issue by smothiki** [deis/builder#224]
https://github.com/deis/charts/blob/master/deis-dev/tpl/deis-objectstorage-secret.yaml

the above secret already includes   bucket and region

**Comment by arschles** [comment]
@smothiki it seems that builder, along with the chart, functions properly, and can be configured as-is. My vote is to remove this from the showstoppers list

**Comment by arschles** [comment]
[Object storage docs](https://github.com/deis/workflow/blob/master/src/installing-workflow/configuring-object-storage.md#credentials) should also be upgraded when this work is done.

**Comment by krancour** [comment]
> Object storage docs should also be upgraded when this work is done.

Related: https://github.com/deis/workflow/issues/61

**Comment by arschles** [comment]
Related issues: https://github.com/deis/slugbuilder/issues/32 and https://github.com/deis/slugrunner/issues/18

**Comment by kmala** [comment]
fixed in #262
