### ISSUE TITLE
git concurrent push to same app locks for ever

### ISSUE THREAD

**Issue by smothiki** [deis/builder#234]
git push to an app sets a MAP value to hold lock for that APP to avoid concurrent pushes to the same APP. If the session was off or git push fails . 
Solutions are encouraged . listing out one of my solution for this problem below 

Solution: git push should hold lock for a specific amount of time.

**Comment by arschles** [comment]
@smothiki this is a duplicate of #220

**Comment by smothiki** [comment]
my bad closing this
