### ISSUE TITLE
git push inconsistencies during app deletion

### ISSUE THREAD

**Issue by smothiki** [deis/builder#235]
An edge case in the builder right now is deletion an APP when the git push is in progress. Eventually the git push fails as the builder hooks to container fails but we are not coming back to user with an Appropriate error why the PUSH failed.

**Comment by arschles** [comment]
:+1: 

Additionally, the intermediate state created by a push should be cleaned up. Ref #214 for part of that work

**Comment by vdice** [comment]
@smothiki is this still intended for the `v2.0-rc1` milestone?

**Comment by arschles** [comment]
bumping from RC1, as this is not critical for the RC

**Comment by bacongobbler** [comment]
I'm fairly certain this was resolved via https://github.com/deis/controller/pull/1096. Closing for now, but if there's a specific error let's open another issue. :)
