### ISSUE TITLE
when building dockerfile app complains about slugs

### ISSUE THREAD

**Issue by rimusz** [deis/builder#240]
```
size of streamed logs 29725
Waiting for the deis/dockerbuild-vanity-jailbird-8ce32ac6-51ced4b0 pod to end. Checking every 100ms for 15m0s
Done
Checking for builder pod exit code
Done
remote: 2016/03/08 21:00:11 Error running git receive hook [Timed out waiting for object in storage, aborting build (Object git/home/vanity-jailbird:git-8ce32ac6/push/slug.tgz didn't exist after 5m0s)]
Polling the S3 server every 500ms for 5m0s for the resultant slug at git/home/vanity-jailbird:git-8ce32ac6/push/slug.tgz
To ssh://git@deis.104.155.59.254.xip.io:2222/vanity-jailbird.git
```

It looks like the minio object storage was not accessible

**Comment by smothiki** [comment]
@rimusz are you using the latest image for builder .

**Comment by smothiki** [comment]
This was fixed in this PR https://github.com/deis/builder/pull/237

**Comment by rimusz** [comment]
installed cluster 8 hours ago, so it must be from yesterday, was preparing for the KubeCon demos, but no luck :(

**Comment by rimusz** [comment]
I see, ok, will try to rebuild new deis cluster tomorrow morning

**Comment by smothiki** [comment]
Thanks . Please let us know if it's not working with the latest images

**Comment by arschles** [comment]
@rimusz @smothiki - I believe this has since been fixed. Closing. Please re-open if you disagree.
