### ISSUE TITLE
Port `make deploy` logic into Makefile from controller

### ISSUE THREAD

**Issue by sgoings** [deis/builder#249]
In workflow/controller we have the ability to deploy the component into a kubernetes cluster via `make deploy` https://github.com/deis/workflow/blob/master/Makefile#L30. We'd like to have similar behavior in this component.

There used to be some similar logic in this repo, but it was eventually rendered inoperable with manifest/chart location changes, and finally removed with #246.

**Comment by Joshua-Anderson** [comment]
This has been done, though it was recently broken by the change to deployments. (See #424)
