### ISSUE TITLE
Region specific URLs not allowed?

### ISSUE THREAD

**Issue by krancour** [deis/builder#264]
If I set the `` environment variable to `s3-us-west-2.amazonaws.com`, for instance, builder crashes and restarts over and over with a complaint that the URL should be `s3.amazonaws.com`.

`s3.amazonaws.com` seems to work, but I _had_ been under the impression that was only the URL for `us-east-1`.  Maybe that URL is actually universal and I just didn't know it.

At any rate, seems to me that region-specific URLs _should_ be allowed.  Altho... not having to specify this at all would be better.

**Comment by arschles** [comment]
@krancour answers inline below:

>If I set the `environment variable to `s3-us-west-2.amazonaws.com`, for instance, builder crashes and restarts over and over with a complaint that the URL should be `s3.amazonaws.com`

This is a [known issue for beta](https://github.com/deis/builder/issues/266). There is a [pull request in the docs](https://github.com/deis/workflow/pull/117) to note this fact.

>At any rate, seems to me that region-specific URLs should be allowed. Altho... not having to specify this at all would be better.

We plan to allow the operator to specify the region in the RC1 release. We haven't yet decided, however, if we'll do so with region-specific URLs or by specifying the region in another configuration value.

I'm closing this in favor of #266.
