### ISSUE TITLE
Support other object storage regions

### ISSUE THREAD

**Issue by smothiki** [deis/builder#266]
Currently, the [Minio client library](https://godoc.org/github.com/minio/minio-go)'s [`MakeBucket`](https://godoc.org/github.com/minio/minio-go#Client.MakeBucket) call is the only one that supports regions. This may be enough to support other regions, but our code doesn't look for the region parameter or pass it to that `MakeBucket` call (see https://github.com/deis/builder/blob/master/pkg/gitreceive/build.go#L103).

For an internal look at the minio-go client logic, see the following lines:

- [Where it detects whether the given URL is an Amazon endpoint](https://github.com/minio/minio-go/blob/c5884ce9ce3ac73b025d0bc58c4d3d72870edc0b/utils.go#L161)
- [Where it fetches the S3 URL](https://github.com/minio/minio-go/blob/4fd28416facdd352b3768635f6d4251cca1445bb/api.go#L601)

**Comment by kmala** [comment]
since we want to move away from minio in rc1.This shouldn't be an issue the PR #262  is merged.

**Comment by arschles** [comment]
Ok, then please add `Fixes #266` to that PR

**Comment by kmala** [comment]
fixed #262
