### ISSUE TITLE
print progress bar or waiting periods

### ISSUE THREAD

**Issue by smothiki** [deis/builder#268]
Right now if the image size is too large like slugrunner or slugbuilder or a dockerfile build which builds a really large image. We are not printing any thing to the ssh session once the build hook to controller is done and waiting for a response code. This makes the ssh session empty and occurs in a loadbalancer response time out. Which results in  unnecessary remote end hung errors .

**Comment by vdice** [comment]
FYI behavior as a result of this bug can be seen in https://github.com/deis/builder/issues/267
