### ISSUE TITLE
git push workflow fails

### ISSUE THREAD

**Issue by arschles** [deis/builder#27]
here's what happens after I register an app, create a new key, and `ssh-add` it:

```console
core@micro-kube ~/example-go $ ./deis keys:add ~/.ssh/id_rsa.pub
Uploading id_rsa.pub to deis... done
core@micro-kube ~/example-go $ ./deis create --no-remote
Creating Application... done, created racing-radiator
remote available at ssh://git@10.3.0.40:2222/racing-radiator.git
core@micro-kube ~/example-go $ git remote set-url deis ssh://git@10.3.0.93:2222/racing-radiator.git
core@micro-kube ~/example-go $ git push deis master
ssh_exchange_identification: read: Connection reset by peer
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by arschles** [comment]
note that the `git remote set-url` command is setting the `deis` URL to that of the `deis-builder` service

**Comment by arschles** [comment]
also note that these commands were run from a kubernetes minion, on a cluster started with [micro-kube](https://github.com/krancour/micro-kube)

**Comment by arschles** [comment]
@smothiki any ideas where to start debugging this? builder produces no logs from the `git push` so maybe I should look in workflow?

**Comment by smothiki** [comment]
its port 2223 I guess?

**Comment by arschles** [comment]
the service says it's exposing port 2222: ```ENG000656:micro-kube aaronschlesinger$ kubectl --namespace=deis get svc
NAME                  LABELS                              SELECTOR                   IP(S)        PORT(S)
deis-builder          heritage=deis                       name=deis-builder          10.3.0.93    2222/TCP
deis-database         heritage=deis                       name=deis-database         10.3.0.196   5432/TCP
deis-etcd-1           app=deis,name=deis-etcd-1           name=deis-etcd-1           10.3.0.180   2380/TCP
                                                                                                  4100/TCP
deis-etcd-discovery   app=deis,name=deis-etcd-discovery   name=deis-etcd-discovery   10.3.0.123   2381/TCP
deis-minio            heritage=deis                       app=deis-minio             10.3.0.66    9000/TCP
deis-registry         heritage=deis                       name=deis-registry         10.3.0.113   5000/TCP
deis-workflow         heritage=deis,routable=true         name=deis-workflow         10.3.0.40    80/TCP
```

**Comment by arschles** [comment]
also, fwiw, the push workflow worked as of last monday, but a lot has changed since then and I just updated my deis cluster on Friday and then this worked. so I can't point to any one piece that may be the culprit

**Comment by smothiki** [comment]
I've been using 2223. 

```
apiVersion: v1
kind: Service
metadata:
  name: deis-builder
  labels:
    heritage: deis
spec:
  ports:
    - name: ssh
      port: 2223
    - name: fetch
      port: 3000
  selector:
    app: deis-builder
```
