### ISSUE TITLE
High CPU usage on AWS cluster

### ISSUE THREAD

**Issue by fagiani** [deis/builder#287]
Builder using high CPU on AWS clusters.
Replication:
Deploy a workflow-dev or workflow-beta1 charts and wait for about one hour, and then do a `docker stats` on the builder container:

    CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O
    3846d98d2cc9        123.87%             22.88 MB / 3.958 GB   0.58%               0 B / 0 B           28.67 kB / 0 B

`top` on the node gives:
```
top - 21:54:23 up 14:31,  1 user,  load average: 2.68, 2.37, 2.28
Tasks: 114 total,   3 running, 103 sleeping,   0 stopped,   8 zombie
%Cpu(s): 58.7 us,  0.8 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si, 40.5 st
KiB Mem:   3865572 total,  3560500 used,   305072 free,   316248 buffers
KiB Swap:        0 total,        0 used,        0 free.  1861688 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
24647 root      20   0   24908  21756      4 S 88.1  0.6  45:22.33 boot
 3983 root      20   0  609148  60620  31492 S  3.9  1.6  17:17.51 kubelet
    3 root      20   0       0      0      0 R  1.0  0.0   1:13.18 ksoftirqd/0
    7 root      20   0       0      0      0 R  1.0  0.0   5:46.98 rcu_sched
   10 root      rt   0       0      0      0 S  1.0  0.0   0:08.62 watchdog/0
 5541 root      20   0 2057032 390208   8296 S  1.0 10.1  43:48.62 java
15137 root      20   0       0      0      0 S  1.0  0.0   0:00.37 kworker/0:0
```
as per `ps faux` i couldn't find any defunct child processes as below:

    root     24647 45.1  0.5  24908 21904 ?        Ssl  20:08  51:03  \_ boot server

This bug is probably related to #280 but PR #283 didn't apparently resolve it

For clarity, `quay.io/deisci/builder:git-434a078` was the image used by the latest available workflow-dev at the moment of this report.

Scaling down/up or deleting the sick builder pod will fix the problem for about another hour...

Also, I couldn't identify any issues within the builder logs...

**Comment by kmala** [comment]
@fagiani the image you used doesn't contain the #283 code changes. Can you please use `quay.io/deisci/builder:git-b0d8941` or `quay.io/deisci/builder:canary` image and see if the issue is still occurring.

**Comment by jeroenvisser101** [comment]
I'm having the exact same issue and I'm using `quay.io/deis/builder:v2.0.0-beta2` as image builder. Also, I think I do have defunct child processes:

![image](https://cloud.githubusercontent.com/assets/1941348/14685449/04d52b68-0735-11e6-9d5d-e352ae0a87b3.png)

**Comment by jeroenvisser101** [comment]
I'm not running on AWS. Restarting also fixed the issue for some time, but some time after it started being noisy again.
