### ISSUE TITLE
[Meta] consolidate into a single Go binary

### ISSUE THREAD

**Issue by arschles** [deis/builder#29]
This is a high level ticket to rewrite parts of builder in Go, and consolidate the various Go binaries into a single one.

We currently have many Go binaries that are built and used by shell scripts. This ticket is for:

1. Porting those shell scripts to Go
2. Moving the functionality in the external binary artifacts into the single builder process.

Since the shell scripts need the external binary artifacts, (1) must happen before (2).

When work on this starts, this ticket should be broken into smaller chunks.

**Comment by arschles** [comment]
as of now, each the individual binaries that the Makefile builds are:

```console
BINARIES := extract-domain extract-types extract-version generate-buildhook get-app-config get-app-values publish-release-controller yaml2json-procfile
```

**Comment by arschles** [comment]
Another related task will be removing or minimizing etcd usage in builder. Much of the integration is used to communicate with [workflow](https://github.com/deis/workflow). See https://github.com/deis/workflow/blob/master/rootfs/bin/boot#L53 and https://github.com/deis/workflow/search?utf8=%E2%9C%93&q=%22%2Fdeis%2Fservices%22&type=Code for pointers on what data is shared between the two.

This task will likely need to be split into a different issue.

**Comment by arschles** [comment]
More notes:

The scripts are auto-generated by confd, and they're both called at https://github.com/deis/builder/blob/master/pkg/git/git.go#L28-L60. The work for this issue will involve replacing confd with code that can watch etcd keys. Reinforcing my last comment, I believe that work exhausts the scope of this issue and a future issue should be opened to reduce or eliminate etcd usage.

**Comment by helgi** [comment]
We should focus on a solution that does not use `etcd` and instead get the information from elsewhere, debating which should happen first tho

**Comment by arschles** [comment]
Agreed. I don't know enough about builder's use of etcd yet to comment intelligently any further though. I want to separate the etcd use from this refactor if at all possible, to avoid making two major changes in the same patch.

Fwiw, my feeling is that it'll be wiser to make this refactor first and then move away from etcd.
