### ISSUE TITLE
Builder shouldn't send logs from build pods unless DEBUG=true

### ISSUE THREAD

**Issue by mboersma** [deis/builder#296]
# Summary

In fixing Docker app `git push` output for #289, it was suggested that builder itself could perhaps implement DEBUG logging output more cleanly or generically.

# Related Issues

#289 and deis/dockerbuilder#46.

**Comment by arschles** [comment]
thinking about this more, not 100% sure about this because the builder needs to output _some_ logs from the {docker,slug}builder pod. it should be up to that pod what to send back. 

admittedly a large and heavy-handed fix, #207 may help solve this. just throwing it out there
