### ISSUE TITLE
Compile kubectl for alpine linux container

### ISSUE THREAD

**Issue by smothiki** [deis/builder#3]
we need kubectl for build pack type builder to launch slugbuilder as a pod

**Comment by arschles** [comment]
@smothiki I have a `kubectl` build that runs in `alpine:3.1

**Comment by smothiki** [comment]
builder/bpbuilder or I can submit it. I'm so close to getting bp builder ready and ready to submit a huge PR

**Comment by arschles** [comment]
ok, I can't upload it to this issue so I'll submit now

**Comment by smothiki** [comment]
Sure
