### ISSUE TITLE
Git push error when IP's of AWS ELB changes

### ISSUE THREAD

**Issue by arkkanoid** [deis/builder#301]
Working with AWS we use a CNAME to connect to the ELB. This is because the LB IPs can change.
When an IP changes I get an error running a git push:
        
    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!    
    IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
    Someone could be eavesdropping on you right now (man-in-the-middle attack)!
    It is also possible that a host key has just been changed.
    The fingerprint for the ECDSA key sent by the remote host is
    ..... 

After that, I've to remove the host in the file .ssh/known_hosts
Is there a way to avoid this warning using the ELB?

**Comment by arschles** [comment]
@arkkanoid the issue you're seeing here is known and we're actively discussing a fix at https://github.com/deis/builder/issues/157. I'm going to close this in favor of #157
