### ISSUE TITLE
Debug messages when using beta2 builder

### ISSUE THREAD

**Issue by gabrtv** [deis/builder#306]
When running `workflow-beta2`, the builder is spitting out debug messages as part of the buildpack output.

### Replication Steps

1. Create a Deis Cluster
2. Register an app
3. `git push deis master` with a buildpack application like example-go

Output is as follows:

```
$ git push deis master
Counting objects: 80, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (75/75), done.
Writing objects: 100% (80/80), 17.83 KiB | 0 bytes/s, done.
Total 80 (delta 33), reused 0 (delta 0)
Starting build... but first, coffee!
2016/04/22 17:01:36 Successfully copied home/outlaw-mainsail:git-779ca3d7/tar to /tmp/slug.tgz
-----> Go app detected
-----> Checking Godeps/Godeps.json file.
-----> Installing go1.6... done
-----> Running: go install -v -tags heroku .
github.com/deis/example-go
-----> Discovering process types
       Procfile declares types -> web
-----> Compiled slug size is 2.2M
2016/04/22 17:01:42 Successfully copied home/outlaw-mainsail:git-779ca3d7/push/slug.tgz to /tmp/slug.tgz
2016/04/22 17:01:42 Successfully copied home/outlaw-mainsail:git-779ca3d7/push/Procfile to /tmp/build/Procfile
Build complete.
...
Launching App...
Done, outlaw-mainsail:v2 deployed to Deis
```

None of those `Successfully copied` messages should be displayed with debug turned off.

**Comment by arschles** [comment]
I believe this is due to the [object-storage-cli](https://github.com/deis/object-storage-cli)'s output. A solution is to make the CLI check for the `$DEBUG` env var and only output if it's set to `1`. I've created https://github.com/deis/object-storage-cli/issues/10 to track

**Comment by jchauncey** [comment]
moving to rc1
