### ISSUE TITLE
Failed git pushes make it impossible to do a second git push

### ISSUE THREAD

**Issue by arschles** [deis/builder#309]
# Summary

As described in https://github.com/deis/builder/issues/204, when a `git push` fails, a second git push will fail with this error message: `[error] Another git push is ongoing`

## If You Are Reporting a Bug

The builder holds a lock on a per-repository basis, which doesn't get released when the `git push` is interrupted or fails for any reason.

### Replication Steps

1. `git push` a repository to an existing app on your Deis beta2 cluster
2. Interrupt the `git push `(i.e. using ctrl+c) while it is ongoing
3. Try to `git push` again

When you do the second `git push` in step 3, you should see the above error message. You may see a slightly different one due to #217 

# Related Issues

- #217 may cause error messages to differ
- #204 gave rise to this issue
- #220 is slightly related because repository unlocks may fail even if they're issued on purpose

**Comment by arkkanoid** [comment]
I get the same error when I destroy and create an app:
    deis destroy -a island-milepost --confirm=island-milepost
    Destroying island-milepost...
    done in 2s
    
    deisv2 create island-milepost
    Creating Application... done, created island-milepost
    Git remote deis added
    
    git push deis master
    exec request failed on channel 0
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.
    
    2016-05-03T07:27:26.666181851Z errorPanic in safely.Go: interface conversion: string is not error: missing method Error

**Comment by arschles** [comment]
This issue will be fixed  by #316

**Comment by arschles** [comment]
Additionally, a refactor should be made after #316 to create a new func that wraps another `func() error` and ensures that the lock is always unlocked somehow. I'll take this on.

**Comment by arschles** [comment]
this is still waiting for #316, so moving to RC1
