### ISSUE TITLE
Fix the closer channel in pkg/sshd/server.go

### ISSUE THREAD

**Issue by arschles** [deis/builder#322]
# Summary

There is a `chan interface{}` in `pkg/sshd/server.go` that acts as a sentinel channel. It is, however, checked in the event loop that accepts incoming socket connections like so:

```go
if len(closer) > 0 {
    <-closer
    // ...
   return nil
}
```

Above the `for`, this comment exists: `// FIXME: Since Accept blocks, closer may not be checked often enough.`. If the closer channel is still needed, that `FIXME` comment should be addressed.

**Comment by vdice** [comment]
ping @arschles as to if this is still scheduled for the `v2.0-rc1` milestone

**Comment by arschles** [comment]
nope, moving into v2
