### ISSUE TITLE
Use Private Registry with Dockerfile

### ISSUE THREAD

**Issue by arkkanoid** [deis/builder#326]
Hi, 
I've some images pushed to Docker Hub private registry and I want to use it with a Dockerfile deployment.
This only works if I pull previously the image on each node, then the app is deployed succesfully.

It's possible to deploy Dockerfile-apps that contains images from a private registry (without pull previously the images)?

**Comment by bacongobbler** [comment]
You can use `deis pull` with `deis regisry:set`, but builder support (which includes Dockerfile builds) is not currently available.

**Comment by arkkanoid** [comment]
Thanks @bacongobbler. It would be nice to have this feature.

**Comment by bacongobbler** [comment]
let's keep this issue open to track this feature. :)

**Comment by kmala** [comment]
fixed by https://github.com/deis/dockerbuilder/pull/101
