### ISSUE TITLE
Pass git receive func() error to sshd.server()

### ISSUE THREAD

**Issue by smothiki** [deis/builder#332]
Right now we are just passing receive type as mock and handling a mock git receive code for unit tests.
Should be able to pass mock gitreceive function to the ssd.server() to execute as a git receive .

**Comment by smothiki** [comment]
refer https://github.com/deis/builder/issues/333

**Comment by bacongobbler** [comment]
We're doing even better by writing unit tests out for the gitreceive target. I think that is the direction we should continue.
