### ISSUE TITLE
refactor the controller utils to the controller env variables

### ISSUE THREAD

**Issue by kmala** [deis/builder#338]
# Summary

currently controller utils(https://github.com/deis/builder/blob/master/pkg/controller/utils.go#L30)  directly gets the values of the environment values instead we should get it through the global configuration file we have(https://github.com/deis/builder/blob/master/pkg/conf/config.go#L29)

## Everything Else
# Related Issues
ref https://github.com/deis/builder/pull/335#discussion_r63078027

**Comment by Joshua-Anderson** [comment]
This still needs to be fixed after switching to using the `controller-sdk-go`. Adding labels.
