### ISSUE TITLE
Cannot deploy dockerfile app with procfile

### ISSUE THREAD

**Issue by bacongobbler** [deis/builder#342]
# Summary

Dockerfile applications with Procfiles are not read.

## If You Are Reporting a Bug

In v1 you were able to deploy a Dockerfile app optionally with a Procfile so you got the best of both worlds. The builder currently reads Procfiles [only if it's a buildpack app](https://github.com/deis/builder/blob/af0bc8c41d55321d0c149ce75fc5206c87d0be8e/pkg/gitreceive/build.go#L235-L239). We should be able to deploy Dockerfile apps with a Procfile, which then the controller can use the Procfile to determine the application's process list.

### Replication Steps

Please provide a detailed list of steps to reproduce it.

1. Create a Deis Cluster
2. Register an app
3. Deploy a Dockerfile app with a Procfile

For example, add the following Procfile to example-go:

```
web: example-go
```

The default process type that is deployed should be `cmd` and `web` should not be present in the application info. In reality the default process type should be `web` and should be present in the application info.

# Related Issues

related: https://github.com/deis/builder/issues/95

**Comment by mboersma** [comment]
See also possibly related deis/workflow-e2e#202.

**Comment by bacongobbler** [comment]
That issue is related but works because the builder is bypassed. :)

**Comment by matthewrudy** [comment]
Nice, thank you.
