### ISSUE TITLE
k8s api rate limit

### ISSUE THREAD

**Issue by aledbf** [deis/builder#343]
# Summary

Updating the k8s dependencies to 1.2 I saw the next output from a build:
```
remote: ---> W0513 02:29:46.517144      26 request.go:627] Throttling request took 67.040356ms, request: GET:https://10.3.0.1:443/api/v1/namespaces/deis/pods/slugbuild-rest-cert-avaluo-fiscal-6d837cb4-ec811c90        
remote: W0513 02:29:46.717168      26 request.go:627] Throttling request took 167.090257ms, request: GET:https://10.3.0.1:443/api/v1/namespaces/deis/pods/slugbuild-rest-cert-avaluo-fiscal-6d837cb4-ec811c90        
remote: W0513 02:29:46.917105      26 request.go:627] Throttling request took 167.006894ms, request: GET:https://10.3.0.1:443/api/v1/namespaces/deis/pods/slugbuild-rest-cert-avaluo-fiscal-6d837cb4-ec811c90 
```

which means the call to wait for the pod is hitting the api server too often.

I think this https://github.com/deis/builder/blob/master/pkg/gitreceive/build.go#L186 function should be refactoring to use a local cache. Something like this:

```
var podLister  cache.StorePodLister

podEventHandler := framework.ResourceEventHandlerFuncs{
  AddFunc: func(obj interface{}) {
    // new build pod
  },
  DeleteFunc: func(obj interface{}) {
    // build pod ended/died
  },
}

podLister.Store, podController = framework.NewInformer(
  &cache.ListWatch{
    ListFunc:  podListFunc(kubeClient, namespace),
    WatchFunc: podWatchFunc(kubeClient, namespace),
  },
  &api.Pod{}, resyncPeriod, podEventHandler)


func podListFunc(c *client.Client, ns string) func(api.ListOptions) (runtime.Object, error) {
  return func(opts api.ListOptions) (runtime.Object, error) {
    // ad condition to only receiver pods related with build operations buildpack/dockerfile
    return c.Pods(ns).List(api.ListOptions{
    })
  }
}

func podWatchFunc(c *client.Client, ns string) func(api.ListOptions) (runtime.Object, error) {
  return func(opts api.ListOptions) (runtime.Object, error) {
    // ad condition to only receiver pods related with build operations buildpack/dockerfile
    return c.Pods(ns).Watch(api.ListOptions{
    })
  }
}
```

and then `waitForPod` can use `podLister` instead of direct calls to kube api server.
This will reduce dramatically the number of calls and remove the rate limit (there's no limit using a local cache)

**Comment by aledbf** [comment]
This is working code https://github.com/aledbf/builder/blob/e29ab9eccc538ae0675adf0d2175a8ca07ecc5de/pkg/k8s/watch.go

**Comment by kmala** [comment]
@aledbf i had seen you code and i understood that you are trying to store a local cache and update the cache every 30 seconds...instead can't we just make the watch for pod call api server only every 30 seconds since local cache isn't going to change for that 30 second period duration or am i missing something?

**Comment by aledbf** [comment]
@kmala is not just a local cache. This also uses a watch to receive incremental updates from the server. The 30 seconds resync is just for the delta.
