### ISSUE TITLE
Proposal: release the push lock when the SSH connection is severed

### ISSUE THREAD

**Issue by arschles** [deis/builder#345]
# Summary

This issue if for detecting when the SSH connection is severed, and releasing the push lock when that happens.

## If You Are Reporting a Bug

If the user doing a `git push` cancels the git push (by doing a ctrl+c, for example), the builder still holds the push lock until the builder pod finishes. Instead, it should immediately release the lock

### Replication Steps

Please provide a detailed list of steps to reproduce it.

1. Create a Deis Cluster
2. Register an app
3. Start a `git push`
4. Cancel it
5. Try to do another `git push`

After #5, you'll notice that the `git push` will fail with an error message until the builder pod finishes. 

# Related Issues

Note that https://github.com/deis/builder/pull/339 fixes the issue where the lock is released when the builder pod _errors_.

**Comment by bacongobbler** [comment]
fixed in #339
