### ISSUE TITLE
Update pkg/gitreceive/config.go w/ v2.0.0 tags

### ISSUE THREAD

**Issue by vdice** [deis/builder#357]
# Summary

Once the `v2.0.0` milestone is closed (v2.0.0 released), the following [values](https://github.com/deis/builder/blob/master/pkg/gitreceive/config.go#L36-L37) need to be updated to point to the appropriate Docker image tags.

**Comment by bacongobbler** [comment]
so v2.0.0 has been using pre-prod slugbuilder/dockerbuilder for a while now? yeesh. Fixing this now.

**Comment by bacongobbler** [comment]
Ah I'm mistaken; the chart [overrides this](https://github.com/deis/charts/blob/master/workflow-v2.0.0/tpl/deis-builder-rc.yaml#L38-L41) so this has been fine.

**Comment by arschles** [comment]
@bacongobbler why not remove the defaults entirely and make those values required?

**Comment by helgi** [comment]
In the Controller we just reference canary :P

**Comment by bacongobbler** [comment]
Indeed. I think that is the better approach. I will amend #376 to do so.
