### ISSUE TITLE
Deis builder does not keep a cache between buildpack deploys

### ISSUE THREAD

**Issue by nathansamson** [deis/builder#380]
# Summary

Deis builder is not keeping an (observable) cache between buildpack builds

### Replication Steps

* Deply an app with git push (preferably an app that would use caching, like a rails app with multiple Gems)
* Wait for a while (in my case more than 15 minutes) for the deploy to finish
* Commit a small change (not to anything that would break the cache, so nothing in the Gemfile)
* Deploy again with git push

I would  expect the second push to go a lot faster as all the Gemfiles and assets should still be in the cache, and should be easily rebuildable. This is not the case.

I am using a stateless cluster, but that should not matter as I expect all state either to be pushed to S3, or stored locally

Note I did not test any other buildpacks except for the rails buildpack, it might actually just be an interaction bug between the buildpack and the slugbuilder

In Deis V1 this worked fine (assuming the builder did not restart)

**Comment by foxycoder** [comment]
I have found the exact same issue. I am on workflow 2.1.0, and I use GCS as a storage backend (not minio).

**Comment by jeroenvisser101** [comment]
Please see https://github.com/deis/slugbuilder/issues/95
