### ISSUE TITLE
Better error message when builder/controller API auth fails

### ISSUE THREAD

**Issue by felixbuenemann** [deis/builder#385]
If the authentication from the builder to the controller fails due to a wrong secret, `deis push` fails with `Permission denied` and the builder logs `[ERROR] Failed handshake: EOF` which does not give any indication of the actual error.

Instead the builder should log something like `[ERROR] API authentication to controller failed` which would be much more useful when debugging the problem.

I ran into this while debugging the problem described in deis/charts#303 where `helmc` generated a builder secret that began with a space and caused the API request to verify the ssh key between builder and controller to fail.

In order to find the cause for the above mentioned issue I had to read the source code for the ssh server, controller utils, the go ssh module docs and construct an API request using `curl` from inside the builder container…

The code that should be augmented is in sshd `server.AuthKey()` calling `controller.UserInfoFromKey()` [without logging anything if this call fails](https://github.com/deis/builder/blob/3e7a785db5402cbd343a5f688d6798ecfe658efc/pkg/sshd/server.go#L40).

This issue is related to #32 and probably others relating to the "Failed handshake: EOF" error.

**Comment by Joshua-Anderson** [comment]
I added a log message when authentication fails in #402.
