### ISSUE TITLE
Pass config to slugbuilder/dockerbuilder during builds

### ISSUE THREAD

**Issue by mattk42** [deis/builder#388]
Both V1 and Heroku support passing config as env vars to the builders, but this is currently missing in workflow. I would like to see this personally as some of my builds rely on specific env vars set to authenticate with external private ruby gem repositories.

**Comment by arschles** [comment]
To add some color on implementation details, one of the two things will need to happen to make this work:

1. The builder needs to query something (probably the controller) to get the env vars for the app to be built and pass them down to the applicable build pod (dockerbuilder or slugbuilder)
2. The build pod (dockerbuilder or slugbuilder, depending on the type of the build) has to do the same query as described in (1)

**Comment by bacongobbler** [comment]
I'm pretty sure we [already do this](https://github.com/deis/builder/blob/d5bcd49cd9c525067eb6f19cb0eb3e805ec9d680/pkg/gitreceive/controller.go#L44-L88) and have been doing so [since 2014](https://github.com/deis/deis/pull/960). Is this untrue in master?

**Comment by kmala** [comment]
yes..whatever is set via `deis config:set <>` should be available to the build environment

**Comment by felixbuenemann** [comment]
It certainly works fine for me. I use a custom buildpack that references environment variables at compile time to generate an nginx config.

**Comment by mattk42** [comment]
Awesome! Sorry for the confusion, I'll go ahead and close this.
