### ISSUE TITLE
Load test deploying apps

### ISSUE THREAD

**Issue by arkkanoid** [deis/builder#427]
Hi, I've done some load tests deploying apps through Git, I deployed 10 apps concurrently. I've found some errors related with the SSH connection but I'm not sure what's  the issue:

    [ERROR] Failed handshake: EOF
    Accepted connection.
    ---> [ERROR] Failed handshake: EOF
    Accepted connection.
    ---> [ERROR] Failed handshake: ssh: invalid packet length, packet too large

---------------------------------------
    [ERROR] Failed git receive: Failed to run git pre-receive hook:  (signal: broken pipe)

**Comment by mboersma** [comment]
The only similar error I'm aware of usually derives from ELB configuration: https://deis.com/docs/workflow/managing-workflow/configuring-load-balancers/#idle-connection-timeouts

It's also possible that the load on the controller or builder caused it to miss a livenessCheck, which could cause Kubernetes to stop routing its traffic temporarily.

@arkkanoid is this with Deis Workflow v2.5.1 or earlier? Do you have a test script or steps to help reproduce this error?

**Comment by arkkanoid** [comment]
The issue is on version v2.4.2.
I simply ran 'git push deis branch' on apps with 15MB of data code. 
I ran it to 10 different apps concurrently.
 2/10 deploys had this error.
The git push is from an EC2 instance to the Deis ELB.
The controller and the builder have 0 restarts.

**Comment by arkkanoid** [comment]
Complete logs:
<script src="https://gist.github.com/arkkanoid/c4d00395d412ff6b0b4f29984b69740c.js"></script>

**Comment by mboersma** [comment]
Just to check, did you increase the AWS ELB timeout to 1200s as recommended in our docs?

**Comment by arkkanoid** [comment]
Yes, I increased it to 2000 sec.

**Comment by mboersma** [comment]
@arkkanoid my apologies for not following up here--I was kind of out of ideas.

Is this still reproducible in current Deis Workflow (v2.6.0)? And do you have an example of one of these apps with 15MB of data code I could use to try to test this?

**Comment by arkkanoid** [comment]
Sorry I solved it few weeks ago. I think it was an error related with the DNS resolution service. I updated it to a new Kubernetes version and it works now.

Thanks!
