### ISSUE TITLE
Failure to put git images to Azure Blob.

### ISSUE THREAD

**Issue by monaka** [deis/builder#428]
Moved from deis/workflow#340.

```
NAMESPACE   NAME                           READY     STATUS    RESTARTS   AGE       NODE
deis      deis-builder-549937908-ohf0y   0/1       CrashLoopBackOff   5         6m        10.0.2.4
```

```
$ kubectl logs   --namespace deis -f deis-builder-549937908-ohf0y                                                                                                                         
2016/09/16 01:32:47 Error creating storage driver (Put https://{censored}.blob.core.windows.net/builder?restype=container: dial tcp: i/o timeout)
m
```

It looks randomly failure.

**Comment by bacongobbler** [comment]
An i/o timeout means that the connection to azure timed out or the connection was lost. Can you try pushing again and confirm that your network connection to Azure Blob Storage is stable?

Also, can you confirm that you're connecting to a datacenter close to your approximate location? Is it correct to assume that your cluster is based near Japan? According to https://azure.microsoft.com/en-us/regions/services/ there appears to be both Japan west and east regions available for Azure Blob Storage.

**Comment by monaka** [comment]
Both Storage and VM are in same region (Japan east).
The storage grade is Standard-LRS. 
And there is no system failure report by Azure.

It is just a guess for now. But it may be caused DNS related issues.

**Comment by monaka** [comment]
I got verbose logs by kube-dns/dnsmasq.

It was queried not only `blob.core.windows.net` but also `blob.core.windows.net.cluster.local`.
Is it expected behavior?

```
dnsmasq: query[A] {censored}.blob.core.windows.net.cluster.local from 172.16.12.25
dnsmasq: cached {censored}.blob.core.windows.net.cluster.local is NXDOMAIN
dnsmasq: query[AAAA] {censored}.blob.core.windows.net.cluster.local from 172.16.12.25
dnsmasq: cached {censored}.blob.core.windows.net.cluster.local is NXDOMAIN
dnsmasq: query[AAAA] {censored}.blob.core.windows.net from 172.16.12.25
dnsmasq: cached {censored}.blob.core.windows.net is <CNAME>
dnsmasq: cached blob.ty1prdstr03a.store.core.windows.net is NODATA-IPv6
dnsmasq: query[A] {censored}.blob.core.windows.net from 172.16.12.25
dnsmasq: cached {censored}.blob.core.windows.net is <CNAME>
dnsmasq: cached blob.ty1prdstr03a.store.core.windows.net is {IP at Azure}
dnsmasq: query[A] {censored}.blob.core.windows.net.cluster.local from 172.16.12.4
dnsmasq: cached {censored}.blob.core.windows.net.cluster.local is NXDOMAIN
dnsmasq: query[AAAA] {censored}.blob.core.windows.net.cluster.local from 172.16.12.4
dnsmasq: cached {censored}.blob.core.windows.net.cluster.local is NXDOMAIN
dnsmasq: query[AAAA] {censored}.blob.core.windows.net from 172.16.12.4
```

**Comment by bacongobbler** [comment]
Yep! That's expected behaviour within kubernetes as the DNS lookup within the containers first tries `.cluster.local` before going outwards, in case there's a service provided that resolves `blob.core.windows.net.cluster.local`.

**Comment by monaka** [comment]
@bacongobbler Thank you for your reply. I see Kube looks sane.
Then suspection points are "DNS throttling by Azure". ... or a bug in Alpine https://github.com/kubernetes/kubernetes/issues/30215 ?.

**Comment by monaka** [comment]
I got it. In this case, the root cause was my misconfiguration.
kubedns/kubedns container was killed continuously by kubedns/healthz. 
Close this issue as it is not by Builder. Thank you for your support.
