### ISSUE TITLE
Set DEIS_DEPLOY_TIMEOUT launch Creating build... Error: Unknown Error (400): {"detail":"Can't convert 'int' object to str implicitly"}

### ISSUE THREAD

**Issue by gslopez** [deis/builder#429]
Hi, i am trying to set the environment variable DEIS_DEPLOY_TIMEOUT to 5 minutes, but when I deploy an image, it launch error. I launched my cluster in AWS, and if I don't set this variable, all works very well.

Here is my terminal output
```sh
$deis version
v2.5.1

$ deis apps:list
=== Apps
app

$ deis config:set DEIS_DEPLOY_TIMEOUT=600 -a app
$ deis config:set PORT=8080 -a app
Creating config... done

=== app Config
DEIS_DEPLOY_TIMEOUT      600
PORT                     8080

$ deis pull deis/example-go:latest -a app
Creating build... Error: Unknown Error (400): {"detail":"Can't convert 'int' object to str implicitly"}
```

**Comment by helgi** [comment]
There is a PR to fix that in Controller already https://github.com/deis/controller/pull/1076 - sorry about the mishap.

@bacongobbler Can you verify that your PR fixes this ticket?

**Comment by bacongobbler** [comment]
Yes, deis/controller#1076 directly addresses this issue.
