### ISSUE TITLE
k8s watcher references missing k8 packages 

### ISSUE THREAD

**Issue by jsimnz** [deis/builder#430]
Currently builder references some missing k8 packages that from what I can tell they recently overhauled that API.

the file pkg/k8s/watch.go references k8s.io/kubernetes/pkg/controller/framework which no longer exists.

Additionally, the PodWatcher struct references *framework.Controller, which no longer exists since controller/framework no longer exists as a package.

Lastly the pw.Store.Store is invalid since StoreToPodLister doesn't have Store as a field.

**Comment by kmala** [comment]
it is refactored into the clients package https://github.com/kubernetes/kubernetes/pull/32718 recently and is not released.
There is plan to uptake https://github.com/kubernetes/client-go once all the dependencies are sorted out and a new version is released.

**Comment by bacongobbler** [comment]
Also note that it is required to use [glide](https://github.com/Masterminds/glide) and not `go get` to install builder's dependencies. [We use v1.2.4](https://github.com/deis/builder/blob/933c1247161bab9c41d0894bff01acf87bfe8c98/glide.yaml#L26) as our baseline which includes the required packages you seek. See https://github.com/kubernetes/kubernetes/tree/v1.2.4/pkg/controller/framework :)
