### ISSUE TITLE
Slugbuilder build with private buildpack repo fails on builder v2.6.0+

### ISSUE THREAD

**Issue by felixbuenemann** [deis/builder#456]
Due to the changes introduced by #444 / #447 the environment variable `SSH_KEY` is no longer passed to the sludbuilder environment, however this variable is required by the build.sh script in slugbuilder to be able to clone buildpacks from private git repos, so this variable needs to be whitelisted.

See https://github.com/deis/slugbuilder/blob/master/rootfs/builder/build.sh#L102

This is related to issues #454 and #455.

**Comment by felixbuenemann** [comment]
**Note:** For other people running into this issue, you can work around it by editing the deis-builder deployment and changing the version of the builder image back to v2.5.5 until a fix is available.

**Comment by kmala** [comment]
fixed in https://github.com/deis/slugbuilder/pull/126
