### ISSUE TITLE
v2.8.0: Dockerfile builds fail with "One or more build-args not consumed, failing build."

### ISSUE THREAD

**Issue by felixbuenemann** [deis/builder#491]
After upgrading deis-builder from v2.7.1 to v2.8.0 and dockerbuilder from v2.6.0 to v2.7.0, Dockerfile builds fails with errors like these:

```
One or more build-args [DATABASE_URL ASSET_ORIGINALS_PREFIX ASSET_S3_REGION DATABASE_URL_DE PORT AWS_SECRET_ACCESS_KEY STEP_IMPORT_LOG_BUCKET IMAGE_PULL_POLICY STEP_IMPORT_LOG_PREFIX APP_ENV ASSET_ORIGINALS_BUCKET RUBYOPT DATABASE_URL_UK AWS_REGION ASSET_INTERMEDIATES_BUCKET VIPS_WARNING AWS_ACCESS_KEY_ID] were not consumed, failing build.
```

It appears to be related to #488.

None of the above environment vars are referenced as ARGS inside the Dockerfile, which is likely the cause of the error.

**Comment by bacongobbler** [comment]
Yep! This issue is being tracked in https://github.com/deis/builder/issues/490. We are currently testing https://github.com/deis/dockerbuilder/pull/118 which should fix this issue.

**Comment by felixbuenemann** [comment]
Oh, my bad for not checking for existing issues. Closing this one.
