### ISSUE TITLE
deis create fails to create a git repo

### ISSUE THREAD

**Issue by Dakuan** [deis/builder#499]
I can create an app with the `--no-remote` option for the walk through and `docker pull` works just fine, but If I want a git repo I get an error
```
[~:dom] ⚡  deis create
Creating Application... done, created haptic-farmland
Error: Error when running 'git remote add deis ssh://git@deis-builder.cluster.fluid.ly:2222/haptic-farmland.git'
fatal: Not a git repository (or any of the parent directories): .git
```

Similarly, if creating a repo after a `--no-remote`:

```[~:dom] ⚡  deis create --no-remote
Creating Application... done, created quoted-sandwich
If you want to add a git remote for this app later, use `deis git:remote -a quoted-sandwich`
[~:dom] ⚡  deis git:remote -a quoted-sandwich
Error: Error when running 'git remote -v'
fatal: Not a git repository (or any of the parent directories): .git```

**Comment by bacongobbler** [comment]
Hi @Dakuan! can you check `git status` in your current working directory?

**Comment by bacongobbler** [comment]
For reference, `heroku create` does not initialize the repository either. It is expected that either the user has cloned an application from a git repository or runs `git init` to start a new one.

**Comment by Dakuan** [comment]
```[~:dom] ⚡  git status
fatal: Not a git repository (or any of the parent directories): .git```

I'm confused - I'm doing all my deis stuff from my home dir - I need to be in the app dir on my local machine to set up a remote repo?

**Comment by bacongobbler** [comment]
> I'm confused - I'm doing all my deis stuff from my home dir - I need to be in the app dir on my local machine to set up a remote repo?

That is correct. Similar to heroku's workflow, the "happy path" would be

```
$ git clone https://github.com/deis/example-go
$ cd go/
$ deis create
$ git push deis master
```

If you are pulling down an image to the cluster via `deis pull`, however, you can do

```
$ deis create --no-remote
$ deis pull deis/example-go
```

Does that help clarify things?

**Comment by Dakuan** [comment]
As you suggest, `deis create` inside a git repo works lovely - thanks

Still a bit confused mind. If I'm at `~/`, I can create a heroku app just fine:

```
[~:dom] ⚡  heroku create
Creating app... done, ⬢ thawing-forest-56676
https://thawing-forest-56676.herokuapp.com/ | https://git.heroku.com/thawing-forest-56676.git
[~:dom] ⚡
```

**Comment by Dakuan** [comment]
all good though, I'm up and running. Greatly appreciate the responsiveness!

**Comment by bacongobbler** [comment]
That is an interesting behaviour. Maybe the Heroku client recognizes that there's no git repo, so it just runs with --no-remote and reports the URL. I can file a feature request for that in deis/workflow-cli.

No problem. Happy to help!

**Comment by bacongobbler** [comment]
I filed https://github.com/deis/workflow-cli/issues/298 to track the feature. Thanks for the report!
