### ISSUE TITLE
create builder pods with a uuid

### ISSUE THREAD

**Issue by arschles** [deis/builder#51]
# Problem
As seen in https://github.com/deis/builder/issues/49, if a build fails for some reason and the user's `git` client believes that the latest rev hasn't been pushed, it's reasonable to think that they will try to `git push` the same rev again.

In that case, builder will try to start a builder pod with the same name (because it computes the pod name based only on the rev). As a defensive measure, it would be useful for the builder pod to also include a random uuid so that even in this error case, the builder can re-build the same git rev.

# Workaround

Before this is fixed, you can make another commit, push again, and builder will successfully name the builder pod something new, based on the new git sha. For example, a `git commit --allow-empty -m "empty"` will do the trick.

# Issue Status
Not marking as showstopper, but keeping it in alpha. Treating this as a nice to have, but required for beta since we have a known workaround in the meantime.

**Comment by arschles** [comment]
moving to beta

**Comment by gabrtv** [comment]
I just hit this:

```
$ git push deis master
...
Error from server: error when creating "/etc/node:git-76460739.yaml": pods "node-git-76460739" already exists
```

Workaround is as follows:

```
$ git commit -m 'bump' --allow-empty
$ git push deis master
```
```
$

**Comment by arschles** [comment]
That's what I've been using to workaround as well. Note that once https://github.com/deis/builder/issues/57 is fixed, we'll be able to reuse slug or dockerbuilder pod names after they successfully exit.

This ticket will address the case where they fail and the user `git push`es the same sha to retry the build.
