### ISSUE TITLE
Cannot find packages "k8s.io/kubernetes/pkg/client/cache" and "k8s.io/kubernetes/pkg/controller/framework"

### ISSUE THREAD

**Issue by pfeodrippe** [deis/builder#510]
I've made a fork of the Deis Builder repo and the command ```$ go test $GOPATH/src/github.com/pfeodrippe/builder/pkg/gitreceve``` is giving me 

```../../../../deis/builder/pkg/k8s/watch.go:7:2: cannot find package "k8s.io/kubernetes/pkg/client/cache" in any of:
	/usr/local/go/src/k8s.io/kubernetes/pkg/client/cache (from $GOROOT)
	/Users/mac/Documents/go-work/src/k8s.io/kubernetes/pkg/client/cache (from $GOPATH)
../../../../deis/builder/pkg/k8s/watch.go:9:2: cannot find package "k8s.io/kubernetes/pkg/controller/framework" in any of:
	/usr/local/go/src/k8s.io/kubernetes/pkg/controller/framework (from $GOROOT)
	/Users/mac/Documents/go-work/src/k8s.io/kubernetes/pkg/controller/framework (from $GOPATH)
```
But these packages doesn't exist at the [kubernetes repo](https://github.com/kubernetes/kubernetes). Is there another way I can test the builder code?

**Comment by bacongobbler** [comment]
You might have to remove your vendor dir and run `make bootstrap` again due to #509.

**Comment by bacongobbler** [comment]
Actually that PR hasn't been merged yet, but did you run `make bootstrap`before running `make test`?

We don't typically run `go test` directly unless you're familiar with glide.

**Comment by pfeodrippe** [comment]
@bacongobbler Ok, it worked! I'll follow this PR. 
Thanks, man
