### ISSUE TITLE
Ability to configure global `prefix/` for Deis-created Docker repositories

### ISSUE THREAD

**Issue by mariusmarais** [deis/builder#519]
We're using the AWS ECR as our registry, of which you can have only one per account.

We want to run multiple Kubernetes clusters (with Deis on top), which causes trouble because the repository names inside the registry are all flat and cause collisions when DeisA and DeisB both have the same app name. (DeisA and DeisB are running completely separately, on different clusters with separate storage and domains.)

Is it possible to create a namespace or `prefix/` for Deis-created repositories, so that `app1` becomes `deisA/app1` ?  If that works correctly, it should also be possible to use IAM to segregate access to the repositories based on the prefix.

**Comment by Cryptophobia** [comment]
This issue was moved to teamhephy/builder#7
