### ISSUE TITLE
Remove the Fetcher

### ISSUE THREAD

**Issue by arschles** [deis/builder#6]
The buildpack builder has a [fetcher](https://github.com/deis/builder/tree/master/bpbuilder/fetcher), which acts as a slug and tar specific network storage system. Its implementation is to store slugs and tars in specific locations on the local filesystem. It appears that the fetcher's goal is to be a fallback in case S3 is not configured for the install.

We're adding support for minio (see `Object Storage` in https://github.com/deis/deis/issues/4743), which is a more general purpose object storage system that can run in the cluster (currently its implementation is also to store data on the filesystem) in v2 Alpha.

I'm proposing that we remove the fetcher and require that either S3 or Minio access is configured for builder and [slugbuilder](http://github.com/deis/slugbuilder).

cc/ @smothiki

**Comment by smothiki** [comment]
+1. I think you already have code in place to avoid fetcher component.
