### ISSUE TITLE
Handle outside storage env variable

### ISSUE THREAD

**Issue by smothiki** [deis/builder#62]
When outside storage env variable is set . We still keep secret mounts in deis-slugrunner and deis-dockerbuilder pods. Unless outside storage requires secrets we should be removing secret mounts from pod yamls

**Comment by arschles** [comment]
This issue will expand in scope if we add RiakCS to the list of object storage options. We'll need to have a lookup order and for various options, not check for secrets...

**Comment by smothiki** [comment]
The new builder code checks for credentials are present or not then add secret mounts . This issue is resolved
