### ISSUE TITLE
Make slugbuilder and dockerimage images configurable

### ISSUE THREAD

**Issue by arschles** [deis/builder#66]
Adapted from deis/workflow#135

The image used for building slugs should be configurable via an environment variable (e.g. `SLUGBUILDER_IMAGE_NAME`) so that a cluster administrator can specify their own image to use. If the environment variable is missing, builder should default to the `quay.io/deisci/slugbuilder` image.

The same requirement will likely apply to the dockerbuilder image, but that's out of scope of this issue.

If so, we have to consider if someone specifies a slugbuilder or dockerbuilder image that's on the internal registry. For example, what happens when someone specifies an image that lives on the internal docker registry, the `docker pull` is in progress, and the registry crashes?

**Comment by helgi** [comment]
Moved out of beta since @technosophos had already bumped the referenced workflow ticket out of the beta
