### ISSUE TITLE
slim down the dependency list for builder

### ISSUE THREAD

**Issue by arschles** [deis/builder#75]
the biggest offender is the below dependency. surely we can replace this

```console
- package: github.com/deis/deis
  subpackages:
  - /buildpack/builder/sshd
  - /pkg/time
```

**Comment by smothiki** [comment]
Subpackage 
 - /buildpack/builder/sshd
this is no longer needed, but /pkg/time we are still using it here https://github.com/deis/builder/blob/master/pkg/types.go

**Comment by arschles** [comment]
thanks @smothiki! I see those usages, but it seems that we're not using `Created` and `Updated` (from https://github.com/deis/builder/blob/master/pkg/types.go#L44-L45) anywhere in the rest of builder.

Do you know if they're used anywhere else?

**Comment by smothiki** [comment]
Yeah , But Created and Updated are the part of config struct . https://github.com/deis/builder/blob/master/pkg/utils_test.go#L60-L69. Whenever we get a config they are present in the config response JSON
```{"owner":"sm","app":"laffa","values":{"BUILDPACK_URL":"https://example.com"},"memory":{},"cpu":{},"tags":{},"uuid":"16e3e453-8a48-40e3-b4a5-b3a79f16542d","created":"2016-01-05T00:56:28UTC","updated":"2016-01-05T00:56:28UTC"}```
One solution make them strings.

**Comment by arschles** [comment]
Makes sense. Another possible solution is copy [the code](https://github.com/deis/deis/blob/master/pkg/time/time.go) into `github.com/deis/pkg`. Doing so would remove the dependency on all of `deis/deis`.

**Comment by arschles** [comment]
addendum to my previous comment - looks like I somehow missed that the code is in https://github.com/deis/pkg/tree/master/time already
