### ISSUE TITLE
[Meta] Replace etcd usage with something else

### ISSUE THREAD

**Issue by arschles** [deis/builder#81]
This should be done after #72. See the table below for analysis

Place it's used | Suggested solution | Status | Idea
------------------- | -------------------------- | -------- | ------
`confd` regenerates the `authorized_keys` file | instead of relying on confd to regenerate it, just call to workflow to get keys on every push | Not Done. Work tracked in #122 | Have builder make an API call to the controller to check the validity of a key for the given app. Tracked in #122 
The git-receive hook relies on the `/deis/controller/builderKey` etcd key | This key holds auth information for builder to talk to workflow. Instead of storing it in etcd, store in a k8s secret. See deis/workflow#245, which is doing this work | Done in #72 | N/A
`rootfs/bin/cleanup` | This removes application directories as applications are deleted (and their deletion is published via etcd) in the controller API | Not Done | Have the controller periodically query the k8s API for apps. [deis/router](https://github.com/deis/router) does something similar.

This issue should remove confd as well.

**Comment by smothiki** [comment]
is this going to be part of rewriting builder in go PR ?

**Comment by arschles** [comment]
You commented just before I saved the description on this issue :) No, it's not going to be part of #72.

I'm aiming to keep #72 as small as possible, because the nature of such a rewrite begs for scope creep...
