### ISSUE TITLE
Use the official workflow client

### ISSUE THREAD

**Issue by arschles** [deis/builder#90]
It's under https://github.com/deis/workflow/tree/master/client/controller, but doesn't have funcs for build hooks. IMO it makes sense to put those funcs into a separate package.

**Comment by arschles** [comment]
Rel: #82

**Comment by technosophos** [comment]
I'm pulling this off of the beta milestone since it isn't required or blocking anything.

**Comment by arschles** [comment]
Related to https://github.com/deis/workflow-cli/issues/18 - perhaps the SDK mentioned there should gain calls to interact with build hooks

**Comment by Joshua-Anderson** [comment]
The SDK is now it's own repository, definitely looks worth looking integrating builder with it.

**Comment by Joshua-Anderson** [comment]
This is done!
