### ISSUE TITLE
USING_DOCKERFILE in builder set to false when Dockerfile and Procfile present

### ISSUE THREAD

**Issue by bacongobbler** [deis/builder#95]
In this case, I'd expect both USING_DOCKERFILE and USING_PROCFILE to be true so that we build the image using the Dockerfile and upload the procfile as the process list to the api server.

As seen [here](https://github.com/deis/builder/pull/72#discussion_r49657820)

**Comment by smothiki** [comment]
The preference order is first docker file > procfile as of now . We are no more using USING_DOCKERFILE variable closing this
